default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost
  username: rails
  password: <%= ENV["DATABASE_RAILS_PASSWORD"] %>

development:
  <<: *default
  database: sample_app_development

test:
  <<: *default
  database: sample_app_test

production:
  <<: *default
  database: sample_app_production
  password: <%= ENV["DATABASE_RAILS_PASSWORD"] %>
